### ISSUE TITLE
Bump version in GitHub Actions Cron section of Readme

### ISSUE THREAD

**Issue by danaument** [karl-cardenas-coding/go-lambda-cleanup#112]
**Describe the bug**
The example code for the [githubs action cron](https://github.com/karl-cardenas-coding/go-lambda-cleanup#github-actions-cron) references an older, non-functional version.

**To Reproduce**
`docker pull ghcr.io/karl-cardenas-coding/go-lambda-cleanup:2.0.0` results in "Error response from daemon: manifest unknown"

**Expected behavior**
The example code should have `VERSION: 2.0.8`

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version: 2.0.8

**Additional context**
I created a PR from a personal fork: https://github.com/karl-cardenas-coding/go-lambda-cleanup/pull/111

**Comment by karl-cardenas-coding** [comment]
@danaument, thanks for the PR. The code snippet is not something I intended to update with every version. It's there more to give the user a template for using this in a GitHub Actions cron use case.  However, I'm happy to accept the PR, and I appreciate your help 😄

**Comment by danaument** [comment]
I figured a PR would make it too easy not to do. 😉

**Comment by karl-cardenas-coding** [comment]
Haha @danaument 100% accurate 😂
