### ISSUE TITLE
Getting "manifest unknown" when trying to update the docker image

### ISSUE THREAD

**Issue by obecker** [karl-cardenas-coding/go-lambda-cleanup#145]
**Describe the bug**
I updated the version of the docker image from 2.0.13 to 2.0.15, but the new version (and also 2.0.14) doesn't seem to exist.

**To Reproduce**
Successful pull (after I deleted my local image):
```
$> docker pull ghcr.io/karl-cardenas-coding/go-lambda-cleanup:2.0.13 
2.0.13: Pulling from karl-cardenas-coding/go-lambda-cleanup
bca4290a9639: Pull complete 
5abdc112eb92: Pull complete 
0801a61d7d92: Pull complete 
d8c0e36bc5a8: Pull complete 
c834a78f358b: Pull complete 
Digest: sha256:3eec25125a780346232f45c9cc3cc6deed8a48c115447139298a2cc20757e10f
Status: Downloaded newer image for ghcr.io/karl-cardenas-coding/go-lambda-cleanup:2.0.13
ghcr.io/karl-cardenas-coding/go-lambda-cleanup:2.0.13
```

Failing pull:
```
$> docker pull ghcr.io/karl-cardenas-coding/go-lambda-cleanup:2.0.15
Error response from daemon: manifest unknown
```

**Desktop (please complete the following information):**
 - OS: macOS 14.7
 - Docker: v4.34.3

**Comment by karl-cardenas-coding** [comment]
Hey @obecker 👋 
Thanks for letting me know about this issue. I'll take a peek later today after work to investigate what's causing this. Thanks again the heads up.

**Comment by karl-cardenas-coding** [comment]
@obecker I see the issue. When I updated Goreleaser I now get `v` as a prefix for the images.  Anything after version 2.0.14 requires the `v` prefix. I'll go ahead and update the docs and examples.  

```
docker pull ghcr.io/karl-cardenas-coding/go-lambda-cleanup:v2.0.15
v2.0.15: Pulling from karl-cardenas-coding/go-lambda-cleanup
cf04c63912e1: Already exists
3befcce54bef: Pull complete
da8d6a9af1e6: Pull complete
945b2adaa4b4: Pull complete
b6fecdfb2c83: Pull complete
Digest: sha256:61e11ffc5b0793e93694ec612c39934586178b8ff1b06266a7c9b0b678f8e605
Status: Downloaded newer image for ghcr.io/karl-cardenas-coding/go-lambda-cleanup:v2.0.15
ghcr.io/karl-cardenas-coding/go-lambda-cleanup:v2.0.15
```

Thank you again for letting me know about this.

**Comment by obecker** [comment]
Thanks for looking into this and the quick response. Using v2.0.15 works like a charm! 😀
