### ISSUE TITLE
Add a flag for lambda name(s)

### ISSUE THREAD

**Issue by darrenoc3** [karl-cardenas-coding/go-lambda-cleanup#17]
**Is your feature request related to a problem? Please describe.**
I only want to run go-lambda-cleanup on some lambdas but not on others. But currently the tool only supports cleaning up all lambdas at the same time. 

**Describe the solution you'd like**
a -lambdaNames flag that reduces the scope to only the name(s) provided

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by karl-cardenas-coding** [comment]
@darrenoc3 Interesting request. I could see situations where a user might pass in a long list of lambdas. I wonder if it's better if the CLI accepts an input file instead 🤔  Thoughts?

**Comment by karl-cardenas-coding** [comment]
@darrenoc3 I went ahead and closed the issue. Let me know if the know if you encounter issues with the new `-l` input file parameter.
