### ISSUE TITLE
v1.0.9 not pulling all pages of lambda versions

### ISSUE THREAD

**Issue by mcramer-billgo** [karl-cardenas-coding/go-lambda-cleanup#21]
**Describe the bug**
Running the latest binary in my account returns only 50 Lambdas - I have more than 100. It looks like the following logic in: `func getAllLambdaVersion(ctx context.Context, svc *lambda.Lambda, item *lambda.FunctionConfiguration) ([]*lambda.FunctionConfiguration, error) ` is not working as expected.

```
pageNum := 0
	err := svc.ListVersionsByFunctionPagesWithContext(ctx, input,
		func(page *lambda.ListVersionsByFunctionOutput, lastPage bool) bool {
			pageNum++
			lambdasLisOutput = append(lambdasLisOutput, page.Versions...)
			return lastPage
		})
	if err != nil {
		returnError = err
	}

```

**To Reproduce**
1. Running :
`glc clean -r us-west-2 -c 5 -s -d `

RETURNS: 

```
INFO[08/25/21] ******** DRY RUN MODE ENABLED ********
INFO[08/25/21] Scanning AWS environment in us-west-2
INFO[08/25/21] ............
INFO[08/25/21] **50 Lambdas identified**
INFO[08/25/21] Current storage size: 688 MB
INFO[08/25/21] **************************
INFO[08/25/21] Initiating clean-up process. This may take a few minutes....
INFO[08/25/21] ............
INFO[08/25/21] ............
INFO[08/25/21] 0 unique versions will be removed in an actual execution.
INFO[08/25/21] 0 B of storage space will be removed in an actual execution.
INFO[08/25/21] Job Duration Time: 5.447513s
```

**Expected behavior**
Expect a full list of lambdas and versions

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 
 - Browser NA
 - Version 10.15.7

**Comment by karl-cardenas-coding** [comment]
@mcramer-billgo the next releases should address this issue. Please let me know if you continue to encounter this issue.

**Comment by mcramer-billgo** [comment]
> @mcramer-billgo the next releases should address this issue. Please let me know if you continue to encounter this issue.

Thanks! Working as expected now.
