### ISSUE TITLE
Functions are incorrectly enumerated during getAlllambda()

### ISSUE THREAD

**Issue by pwood** [karl-cardenas-coding/go-lambda-cleanup#25]
**Describe the bug**
When running GLC without a predefined list of lambdas to clean, the getAlllambda() function lists all function versions, rather than just functions.

This results in a multiplication of work in the getAllLambdaVersion() function, as it then in turn lists all the versions for each entry returned by getAlllambda().

In large AWS deployments this results in the process taking an extremely long time, or often erroring due to exceeding AWS rate limits.

For example:

If there is 1 lambda, with 100 versions, getAlllambda() will return 100 entries, which then getAllLambdaVersion will enumerate each of the 100, returning another 100 versions.

So the resulting version count enumerated is 100 * 100, not the correct 100. This results in wrong statistics on dry runs, and duplicated deletion attempts on real runs.

**To Reproduce**
1. Run glc without a predefined version list on a large account, the behaviour can be seen during a dry run: ./glc clean -r eu-west-1 -c 5 -s -v -d

**Expected behavior**
The tool lists the functions once, then enumerates versions. Rather than reenumerating all versions for each function version.

**Screenshots**

Example of incorrect behaviour:
```
+ ./glc clean -r eu-west-1 -c 5 -s -d
time=02/14/22 level=info msg="******** DRY RUN MODE ENABLED ********"
time=02/14/22 level=info msg="Scanning AWS environment in eu-west-1"
time=02/14/22 level=info msg=............
time=02/14/22 level=info msg="739 Lambdas identified"
time=02/14/22 level=info msg="Current storage size: 878 GB"
time=02/14/22 level=info msg="**************************"
time=02/14/22 level=info msg="Initiating clean-up process. This may take a few minutes...."
time=02/14/22 level=info msg=............
time=02/14/22 level=info msg=............
time=02/14/22 level=info msg="145635 unique versions will be removed in an actual execution."
time=02/14/22 level=info msg="850 GB of storage space will be removed in an actual execution."
time=02/14/22 level=info msg="Job Duration Time: 4.453397m"
```

Corrected behaviour by removing the ALL parameter of the FunctionVersions variable in the input struct for ListFunctionsPagedWithContext.

```
go-lambda-cleanup % ./glc clean -r eu-west-1 -c 5 -s -d
INFO[02/14/22] ******** DRY RUN MODE ENABLED ********       
INFO[02/14/22] Scanning AWS environment in eu-west-1        
INFO[02/14/22] ............                                 
INFO[02/14/22] 12 Lambdas identified                        
INFO[02/14/22] Current storage size: 5.0 GB                 
INFO[02/14/22] **************************                   
INFO[02/14/22] Initiating clean-up process. This may take a few minutes.... 
INFO[02/14/22] ............                                 
INFO[02/14/22] ............                                 
INFO[02/14/22] 677 unique versions will be removed in an actual execution. 
INFO[02/14/22] 4.6 GB of storage space will be removed in an actual execution. 
INFO[02/14/22] Job Duration Time: 5.468249s 
```

**Desktop (please complete the following information):**
 - OS: linux/macos
 - Version: 1.0.10

**Additional context**
This is easily fixable by removing this line:
https://github.com/karl-cardenas-coding/go-lambda-cleanup/blob/main/cmd/clean.go#L429

It's easy not to notice this behaviour on small AWS environments.

**Comment by karl-cardenas-coding** [comment]
Hi @pwood thank you for opening this issue and addressing the root cause. I'm opening a PR to address the issue and will release an updated version today.
