### ISSUE TITLE
Install docs are inconsistent 

### ISSUE THREAD

**Issue by dannysauer** [karl-cardenas-coding/go-lambda-cleanup#4]
It's a minor thing, but the install block in the Readme uses a URL for Darwin-arm, but then the unzip refers to the intel-amd64. There should probably be a curl or wget or similar on the URL, too. :)

Thanks for open sourcing your code, though. That's great, especially at SF.

**Comment by karl-cardenas-coding** [comment]
@dannysauer Thank you so much for pointing this out. I'll get this squared away asap.
