### ISSUE TITLE
Add --noop or --dryrun flag/option

### ISSUE THREAD

**Issue by wiggy171** [karl-cardenas-coding/go-lambda-cleanup#7]
Would be nice to have a --noop or --dryrun option where tool would identity _potential_ actions 

--noop or --dryrun (take your pick) would simply identify and report what will be done (kinda similar to a terraform "plan")

Thanks

**Comment by karl-cardenas-coding** [comment]
@wiggy171 Thanks for the feature request. I agree, this would be a helpful feature.  I'll go ahead and get started on this feature request.
